Develop
sniskorodnova/java-explore-with-me pull request #1
Opened 2022-09-22 17:45 UTC by sniskorodnova

Реализация приложения java-explore-with-me

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/category/Category.java
> +    private Long id;
[Нужно исправить] Не хватает аннотации, которая запретит полю id принимать значения null.

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/category/Category.java
> +    @Column(nullable = false)
[Нужно исправить] Нужно добавить аннотацию, которая делает поле name  уникальным.

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/category/CategoryDto.java
> +public class CategoryDto {
[Нужно исправить] Нужно добавить аннотации запрещающие полю id принимать значения null, а полю  name - пустые или пробельные значения.

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/category/CategoryMapper.java
> +                null,
[Нужно исправить]  Нужно переделать код таким образом, чтобы поле id не было null. Id является внешним ключом, поэтому не может принимать значение Null. Каким будет значение поля id при вызове new Category(); Если учесть, что поле id имеет аннотацию  @GeneratedValue(strategy = GenerationType.IDENTITY)?

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/category/CategoryMapper.java
> +public class CategoryMapper {
[Можно улучшить]

Можно показать, что у данного класса не может быть состояний, так как все методы статичны, с помощью @NoArgsConstructor(access = AccessLevel.PRIVATE) таким образом мы запретим создание объектов класса  CategoryMapper

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/category/NewCategoryDto.java
> +    private String name;
[Нужно исправить] 

Нужно добавить аннотацию полю name, запрещающию пустые или пробельные значения.

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/controller/CategoryController.java
> +    public List<CategoryDto> getAll(@RequestParam Integer from, @RequestParam Integer size) {
[Нужно исправить] Нужно добавить значения from и size по умолчанию.

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/service/category/CategoryService.java
> +public interface CategoryService {
[Отлично]

Прекрасная идея вынести логику работы в интерфейс!

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/service/category/CategoryServiceImpl.java
> +@Service
[Нужно исправить]

Подумате, как использовать аннотацию @Transactional в данном классе.

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/service/category/CategoryServiceImpl.java
> +        for (Category category : categoryRepository.findAllByOrderByIdAsc(PageRequest.of(from / size, size))) {
[Нужно исправить]

От цикла нужно избавиться используюя вызов метода categoryRepository.findAll();

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS category (
[Отлично] 

Прекрасная работа, таблица описана верно, вдумчиво подобраны типы и размеры полей!

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/resources/schema.sql
> +    email VARCHAR(512) NOT NULL,
[Можно лучше]
512 многовато для email адреса. 

А в остальном всё отлично!

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/users/User.java
> +    private Long id;
[Нужно исправить] Не хватает аннотации, которая запретит полю id принимать значения null.

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/users/User.java
> +    private String email;
[Нужно исправить] Нужно добавить аннотацию, которая делает поле name уникальным.

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/users/UserDto.java
> +public class UserDto {
[Нужно исправить] Нужно добавить аннотации запрещающие полю id принимать значения null, а полю name - пустые или пробельные значения, а полю email  аннотацию @Email. Использовать эти аннотации нужно по группам, например 
`@Email
    @NotBlank(groups = {Create.class, Update.class})
    private String email;`

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/users/UserMapper.java
> +public class UserMapper {
[Можно улучшить]

Можно показать, что у данного класса не может быть состояний, так как все методы статичны, с помощью @NoArgsConstructor(access = AccessLevel.PRIVATE) таким образом мы запретим создание объектов класса

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/users/UserMapper.java
> +                null,
[Нужно исправить] Нужно переделать код таким образом, чтобы поле id не было null. Id является внешним ключом, поэтому не может принимать значение Null. Каким будет значение поля id при вызове new User(); Если учесть, что поле id имеет аннотацию @GeneratedValue(strategy = GenerationType.IDENTITY)?

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/users/NewUserDto.java
> +public class NewUserDto {
[Нужно исправить]

Нужно добавить аннотацию полю name, запрещающию пустые или пробельные значения.
А полю email добавить аннотацию, проверяющую корректнсть адреса - @Email

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/controller/CategoryController.java
> +        if (userHeader == null) {
[Нужно исправить] после использования аннотаций в классе DTO, нужно заменить подобные проверки на использование аннотации валидации.

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/controller/UserController.java
> +            throw new NoHeaderException("No header in the request");
[Нужно исправить] после использования аннотаций в классе DTO, нужно заменить подобные проверки на использование аннотации валидации.

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/controller/UserController.java
> +    public List<UserDto> getAll(@RequestHeader(value = "X-Sharer-User-Id", required = false) Long userHeader,
[Нужно исправить] Нужно добавить значения from и size по умолчанию.

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/service/users/UserService.java
> +public interface UserService {
[Отлично]

Прекрасная идея вынести логику работы в интерфейс!

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/service/users/UserService.java
> +
[Нужно исправить]

Нужно добавить получение пользователей по ID

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/service/users/UserServiceImpl.java
> +public class UserServiceImpl implements UserService {
[Нужно исправить]

Подумате, как использовать аннотацию @transactional в данном классе.

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/service/users/UserServiceImpl.java
> +        for (User user : userRepository.findAllByOrderByIdAsc(PageRequest.of(from / size, size))) {
[Нужно исправить]

От цикла нужно избавиться используюя вызов метода userRepository.findAll();

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS location (
[Отлично] отличная идея вынести адрес в отдельную таблицу, так как один и тот же адрес может использоваться для разных событий!

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/resources/schema.sql
> +    lat NUMERIC NOT NULL,
[Нужно исправить]

Для координат нужно использовать тип FLOAT

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/resources/schema.sql
> +    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
[Нужно переделать]
не хватает полей  published_on и created_on

 "createdOn": {
            "type": "string",
            "description": "Дата и время создания события (в формате \"yyyy-MM-dd HH:mm:ss\")",
            "example": "2022-09-06 11:00:23"
          },

"publishedOn": {
            "type": "string",
            "description": "Дата и время публикации события (в формате \"yyyy-MM-dd HH:mm:ss\")",
            "example": "2022-09-06 15:10:05"
          },

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/event/Event.java
> +public class Event {
[Нужно исправить]

Необходимо добавить недостающие поля(см. комментарии к schema.sql)

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/event/Event.java
> +    private Long id;
[Нужно исправить] Не хватает аннотации, которая запретит полю id принимать значения null.

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/event/Event.java
> +    private Long categoryId;
[Нужно исправить] Не хватает аннотации @JoinColumn

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/location/Location.java
> +    private Long id;
[Нужно исправить] Не хватает аннотации, которая запретит полю id принимать значения null.

2022-09-25 10:12 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/event/EventDto.java
> +public class EventDto {
[Нужно исправить] Нужно добавить аннотации запрещающие некоторым полям  принимать значения null, а некоторым пустые значения, так же событие должно быть в будущем (аннотация  @nonnull), а лимит участвиков число неотрицательное( @PositiveOrZero)

2022-09-25 17:13 UTC, damirovna requested changes
Выделила основыне замечания в сущностях Category и User. Аналогичные изменения нужно внести в остальные классы.

Самый большой приоритет исправлений id, которые могут быть null - это недопустимо, просьба исправить. 

Второй важный момент: отсутствие всех необходимых  полей в сущности event.

Третий момент: упущена реализация некоторой логики, пожалуйста перепроверьте соответствие реализации и тз, лучше всего пройтись по всем эндпоинтам и проверить, в этом здорово помогут автотесты в графе checks к pull request. Если будут вопросы по тестам - смело пишите их наставнику.

2022-09-25 17:13 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/event/EventMapper.java
> +                null,
[Нужно исправить] Аналогично с классами пользователя и категории.

2022-09-25 17:13 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/event/EventMapper.java
> +                null,
[Нужно исправить] Данные поля не должны быть null

2022-09-25 17:13 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/event/EventDtoWithViews.java
> +public class EventDtoWithViews {
[Нужно исправить] Нужно добавить аннотации запрещающие некоторым полям принимать значения null, а некоторым пустые значения, так же событие должно быть в будущем (аннотация @nonnull), а лимит участвиков число неотрицательное( @PositiveOrZero)

2022-09-25 17:13 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/event/EventState.java
> +public enum EventState {
[Отлично] Тут всё верно!

2022-09-25 17:13 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/event/NewEventDto.java
> +public class NewEventDto {
[Нужно исправить] Нужно будет добавить поля, после того, как в классе Event будут обозначены аннотациями обязательные поля, например в NewEventDto нет пользователя создавшего событие, а должен быть.

2022-09-25 17:13 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/event/NewShortEventDto.java
> +    private Long id;
[Нужно исправить] 

id не должен быть null

2022-09-25 17:13 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/service/event/EventService.java
> +public interface EventService {
[Отлично]

Прекрасная идея вынести логику работы в интерфейс!

2022-09-25 17:13 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/controller/EventController.java
> +    private final EventService eventService;
[Нужно исправить]

В каждом из методов нужно избавиться от if и выброса исключений, вместо этого нужно использовать аннотации валидации

2022-09-25 17:13 UTC, damirovna commented on ewm-service/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS compilation (
[Отлично]

Прекрасная работа, таблица описана верно, вдумчиво подобраны типы и размеры полей!

2022-09-25 17:13 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/compilation/Compilation.java
> +    private Long id;
[Нужно исправить] Не хватает аннотации, которая запретит полю id принимать значения null.

2022-09-25 17:13 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/compilation/CompilationDto.java
> +public class CompilationDto {
[Нужно исправить]

Замечания аналогичные классам CategoryDto и UserDto

2022-09-25 17:13 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/compilation/CompilationMapper.java
> +                null,
[Нужно исправить]

Замечания аналогичные классам CategoryMapper и UserMapper

2022-09-25 17:13 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/compilation/NewCompilationDto.java
> +    private String title;
[Нужно исправить]

Нужно добавить аннотацию полю title, запрещающию пустые или пробельные значения.

2022-09-25 19:33 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/controller/EventController.java
> +    private final EventService eventService;
поправлено

2022-09-25 19:36 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/category/Category.java
> +    @Column(nullable = false)
поправлено

2022-09-25 19:44 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/category/Category.java
> +    private Long id;
поправлено

2022-09-25 19:57 UTC, sniskorodnova commented on ewm-service/src/main/resources/schema.sql
> +    email VARCHAR(512) NOT NULL,
изменила на 64 символа

2022-09-25 20:22 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/controller/CategoryController.java
> +        if (userHeader == null) {
проверки убраны из контроллеров, перехватывается и обрабатывается исключение в RestExceptionHandler

2022-09-25 20:25 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/controller/UserController.java
> +    public List<UserDto> getAll(@RequestHeader(value = "X-Sharer-User-Id", required = false) Long userHeader,
добавлено

2022-09-25 20:27 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/service/users/UserService.java
> +
там есть метод получения пользователей по id ниже
List<UserDto> getAllByIds(List<Integer> ids);

2022-09-25 20:40 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/controller/CategoryController.java
> +    public List<CategoryDto> getAll(@RequestParam Integer from, @RequestParam Integer size) {
добавлено

2022-09-25 20:43 UTC, sniskorodnova commented on ewm-service/src/main/resources/schema.sql
> +    lat NUMERIC NOT NULL,
исправлено

2022-09-25 20:46 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/category/CategoryMapper.java
> +public class CategoryMapper {
исправила для всех классов-мапперов

2022-09-25 20:47 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/users/UserMapper.java
> +public class UserMapper {
исправлено

2022-09-25 20:47 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/controller/UserController.java
> +            throw new NoHeaderException("No header in the request");
проверка убрана, перехватывается исключение, если отсутствует хедер

2022-09-25 21:00 UTC, sniskorodnova commented on ewm-service/src/main/resources/schema.sql
> +    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
добавлено два поля в схему

2022-09-25 21:06 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/event/Event.java
> +    private Long categoryId;
у меня поле типа Long, тут не нужна такая аннотация, она бы понадобилась, если было бы поле
private Category category;

2022-09-25 21:08 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/event/Event.java
> +public class Event {
поля добавлены

2022-09-25 21:37 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/service/category/CategoryServiceImpl.java
> +        for (Category category : categoryRepository.findAllByOrderByIdAsc(PageRequest.of(from / size, size))) {
findAll() так же вернет список List<Category>, мне его нужно преобразовать в список List<CategoryDto>, поэтому так же придется использовать цикл. Ну и я хотела также использовать кастомный метод, чтобы категории выводились отсортированными

2022-09-25 21:49 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/service/users/UserServiceImpl.java
> +        for (User user : userRepository.findAllByOrderByIdAsc(PageRequest.of(from / size, size))) {
Так же как и в категориях findAll() вернет список `List<User>`, который мне надо преобразовать в `List<UserDto>`, поэтому так же придется использовать цикл

2022-09-26 17:06 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/service/users/UserServiceImpl.java
> +public class UserServiceImpl implements UserService {
добавила к методам

2022-09-26 17:06 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/service/category/CategoryServiceImpl.java
> +@Service
добавила к методам

2022-09-26 20:08 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/category/CategoryDto.java
> +public class CategoryDto {
добавлено

2022-09-26 20:09 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/category/NewCategoryDto.java
> +    private String name;
добавлено

2022-09-26 20:19 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/category/CategoryMapper.java
> +                null,
в сервис добавлен метод получения следующего id, который присваивается объекту перед сохранением в базу

2022-09-26 20:21 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/users/User.java
> +    private Long id;
добавлено

2022-09-26 20:23 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/users/User.java
> +    private String email;
тут не совсем согласна, поставила unique для емейла. в моем понимании имя может быть неуникальным, может же быть несколько людей с одинаковыми именами и фамилиями, а вот емейл не должен повторяться

2022-09-26 20:24 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/users/UserMapper.java
> +                null,
в сервис добавлен метод для получения следующего id, который присваивается объекту перед сохранением в базу

2022-09-26 20:56 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/users/UserDto.java
> +public class UserDto {
добавлено

2022-09-26 20:57 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/users/NewUserDto.java
> +public class NewUserDto {
добавлено

2022-09-26 21:01 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/event/Event.java
> +    private Long id;
исправлено

2022-09-26 21:03 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/location/Location.java
> +    private Long id;
добавлено

2022-09-27 14:35 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/event/Event.java
> +    private Long id;
делать не нужно

2022-09-27 14:35 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/category/Category.java
> +    private Long id;
делать не нужно

2022-09-27 14:36 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/category/CategoryMapper.java
> +                null,
делать не нужно

2022-09-27 14:36 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/users/User.java
> +    private Long id;
делать не нужно

2022-09-27 14:37 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/users/UserMapper.java
> +                null,
делать не нужно

2022-09-27 14:38 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/location/Location.java
> +    private Long id;
делать не нужно

2022-09-27 14:38 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/event/EventDto.java
> +public class EventDto {
добавлены аннотации

2022-09-27 14:38 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/event/EventMapper.java
> +                null,
делать не нужно

2022-09-27 14:39 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/event/EventMapper.java
> +                null,
делать не нужно

2022-09-27 14:39 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/event/EventDtoWithViews.java
> +public class EventDtoWithViews {
добавлены аннотации

2022-09-27 14:41 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/event/NewEventDto.java
> +public class NewEventDto {
NewEventDto - это дто, которое по апи присылает клиент, в нем не будет пользователя, он присваивается в сервисе при создании объекта Event, который потом сохраняется в базу. а отдаем клиенту уже EventDto, где поля есть

2022-09-27 14:41 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/event/NewShortEventDto.java
> +    private Long id;
исправлено

2022-09-27 14:41 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/compilation/Compilation.java
> +    private Long id;
делать не нужно

2022-09-27 14:41 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/compilation/CompilationMapper.java
> +                null,
делать не нужно

2022-09-27 14:41 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/compilation/CompilationDto.java
> +public class CompilationDto {
добавлены аннотации

2022-09-27 14:42 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/compilation/NewCompilationDto.java
> +    private String title;
добавлены аннотации

2022-09-28 16:16 UTC, damirovna reviewed
Поздравляю! Добавьте одно исправление и ваша дипломная работа будет принята!

2022-09-28 16:16 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/service/category/CategoryServiceImpl.java
> +        for (Category category : categoryRepository.findAllByOrderByIdAsc(PageRequest.of(from / size, size))) {
Хорошо

2022-09-28 16:16 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/users/User.java
> +    private String email;
Согласна

2022-09-28 16:16 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/storage/event/EventRepository.java
> +            + "where (upper(event.title) ilike upper(concat('%', :text, '%')) "
[Можно лучше]

А зачем ilike, когда обе части и так приведены к апперсейсу?

2022-09-28 16:16 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/service/users/UserService.java
> +
Ага, увидела

2022-09-28 16:16 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/ewm/model/compilation/Compilation.java
> +    Set<Event> events;
[Нужно исправить]

Сет событий должен быть приватным.

2022-09-28 17:11 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/compilation/Compilation.java
> +    Set<Event> events;
поправлено

2022-09-28 17:11 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/storage/event/EventRepository.java
> +            + "where (upper(event.title) ilike upper(concat('%', :text, '%')) "
заменила на like

2022-09-28 17:15 UTC, damirovna approved these changes

2022-10-05 16:50 UTC, merged