Add comments
sniskorodnova/java-explore-with-me pull request #2
Opened 2022-09-28 20:37 UTC by sniskorodnova

Реализация дополнительной функциональности - комментарии

2022-09-29 07:13 UTC, MishaSmr commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentServiceImpl.java
> +     * Оставить комментарий можно только к опубликованному событию, дата которого в прошлом.
Я думаю можно не только к прошедшим, а к любым опубликованным, все таки это не отзывы, а комментарии (ну, например, можно же написать "а что с собой брать" или "в прошлом году был на таком, в этом году не советую никому")

2022-09-29 07:22 UTC, MishaSmr commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentServiceImpl.java
> +    public CommentDto create(Long userId, Long eventId, NewCommentDto newComment) {
Кажется, надо @Transactional

2022-09-29 07:29 UTC, MishaSmr reviewed
Основной вопрос - надо ли комментировать только прошедшие события?

2022-09-29 13:54 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentServiceImpl.java
> +    public CommentDto create(Long userId, Long eventId, NewCommentDto newComment) {
да, добавила

2022-09-29 13:55 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentServiceImpl.java
> +     * Оставить комментарий можно только к опубликованному событию, дата которого в прошлом.
хорошая идея, да. убрала проверку на дату, также убрала ограничение на количество отзывов к событию от одного пользователя, так как тогда пользователь сможет например отвечать на вопросы других пользователей и оставлять несколько комментариев

2022-09-29 13:58 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentServiceImpl.java
> +     * Оставить комментарий можно только к опубликованному событию, дата которого в прошлом.
также добавила возможность владельцу события оставлять комментарии в случае, если он хочет ответить на какой-то вопрос

2022-09-29 14:09 UTC, MishaSmr approved these changes
Good job!

2022-10-03 14:38 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/ewm/controller/comment/AdminCommentController.java
> +        log.info("Входящий запрос на публикацию админом комментария с id = " + commentId);
[nit] я бы здесь сделал уровень логирования дебаг, чтобы не засорять логи. смысловой нагрузки это логирование особо не несет и его можно держать отключенным по дефолту

2022-10-03 14:38 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/ewm/controller/comment/AdminCommentController.java
> +        log.info("Входящий запрос на публикацию админом комментария с id = " + commentId);
_применимо здесь и дальше_

2022-10-03 14:40 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentServiceImpl.java
> +        if (commentRepository.findById(commentId).isEmpty()) {
здесь и на строчке 96 ты вызываешь один и тот же метод. по идее должен отработать кэш, но я бы не надеялся на него в общем случае. 

давай единожды заберем объект по айдишнику

2022-10-03 14:40 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentServiceImpl.java
> +        if (commentRepository.findById(commentId).isEmpty()) {
_применимо здесь и в остальных методах_

2022-10-03 14:42 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentServiceImpl.java
> +                    || commentRepository.findById(commentId).get().getStatus().equals(CommentStatus.PUBLISHED))) {
тут броситься исключение, если комментарий уже зареджекчен. воспроизведется на двух одновременно посланных реквестах на отклонение комментария.

может завершить работу без выброса исключения?

2022-10-03 14:44 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentServiceImpl.java
> +    public CommentDto rejectByAdmin(Long commentId) {
[nit] два уровня вложенности можно сократить до одного.

1. получить объект (0 уровень вложенности)
2. выполнить проверки (1 уровень вложенности)
3. исполнить логику (0 уровень вложенности)

2022-10-03 14:44 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentServiceImpl.java
> +    public CommentDto rejectByAdmin(Long commentId) {
_применимо здесь и в остальных методах_

2022-10-03 14:46 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentServiceImpl.java
> +            }
[nit] можно упростить с помощью стримов
```
 commentRepository.findByEventIdAndStatus(eventId, CommentStatus.PUBLISHED)
    .stream()
    .map(CommentMapper::toCommentDto)
    .toList()
```

2022-10-03 14:46 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentServiceImpl.java
> +            }
_применимо здесь и дальше_

2022-10-03 14:48 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentServiceImpl.java
> +            } else {
здесь будет брошено исключение, если заявка уже заапрувлена. как и в случае реджекта, давай не будем делать ничего

2022-10-03 14:50 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentServiceImpl.java
> +public class CommentServiceImpl implements CommentService {
*Impl считается устаревшим неймингом, смысловой нагрузки минимум. старайся не использовать его по возможности.

зачем нужен интерфейс с единственной реализацией?

2022-10-03 14:50 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentService.java
> +    List<CommentDto> getAll(Long eventId);
Сервис должен возвращать доменный объект и никак не dto.

2022-10-03 14:51 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentService.java
> +    CommentDto create(Long userId, Long eventId, NewCommentDto newComment);
почему аргументы здесь врапперы примитивов, а не сами примитивы?

2022-10-03 14:52 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentService.java
> +    CommentDto rejectByAdmin(Long commentId);
[nit] я бы вынес эти 2 метода в CommentModerationService, чтобы разделить области ответственности

2022-10-03 14:54 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentService.java
> +    CommentDto update(Long userId, Long commentId, NewCommentDto newComment);
[nit] принимается NewCommentDto на апдейт. не получится ли так, что поля на создание и на апдейт в какой-то момент разъедутся? может лучше сделать свою DTO на апдейт?

2022-10-03 14:56 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/ewm/model/event/EventMapper.java
> +                null
метод называется withViews, хотя объект создается без views.
почему бы не передать показы в качестве аргументов к методу?

2022-10-03 15:00 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentService.java
> +    CommentDto update(Long userId, Long commentId, NewCommentDto newComment);
в сервисах в аргументах лучше всего также оперировать доменными объектами.

я бы сделал так:

```
interface CommentService {
    ...
    Comment create(..., CommentContent content);
    Comment update(..., CommentContent newContent);
    ...
}

class NewCommentInputDto {
  private final String text;

  public Comment.Content getContent() {
    return new Comment.Content(text);
  }
}

class UpdateCommentInputDto {
  private final String text;

  public Comment.Content getContent() {
    return new Comment.Content(text);
  }
}
```

2022-10-03 15:03 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/ewm/controller/comment/PrivateCommentController.java
> +    @PostMapping("/users/{userId}/events/{eventId}/comments")
точно ли нужен /users/{userId} в префиксе?

у тебя же есть `@RequestHeader(value = "X-Sharer-User-Id") Long userHeader` в качестве авторизации

2022-10-03 15:03 UTC, vbutrim requested changes
хорошая понятная работа.
есть пара вопросов по логике работы. я бы чуть почистил кодешник и чуть-чуть пересмотрел бы API

2022-10-03 15:06 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/ewm/controller/comment/PrivateCommentController.java
> +    }
что будет, если комментариев под событием оч много?

2022-10-03 15:13 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/controller/comment/AdminCommentController.java
> +        log.info("Входящий запрос на публикацию админом комментария с id = " + commentId);
поменяла

2022-10-03 16:12 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentServiceImpl.java
> +public class CommentServiceImpl implements CommentService {
убрала интерфейс, поменяла название сервиса

2022-10-03 16:55 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/controller/comment/PrivateCommentController.java
> +    @PostMapping("/users/{userId}/events/{eventId}/comments")
я здесь делала по аналогии с основными сервисами, там тоже в запросах использовался /users/{userId}, например /users/{userId}/events/{eventId}/requests/{reqId}/confirm. я так понимаю, что это сделано из-за того, что мы никак не используем хедер. то есть мы его проверяем только на наличие, если запрос требует авторизации, но вообще конечно его надо использовать. в данном случае сделала так из-за реализации апи основного сервиса такого

2022-10-03 17:09 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentService.java
> +    CommentDto rejectByAdmin(Long commentId);
вынесла отдельно

2022-10-03 17:43 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/controller/comment/PrivateCommentController.java
> +    }
добавила пагинацию

2022-10-03 17:46 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentServiceImpl.java
> +            }
переделала

2022-10-03 18:00 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentServiceImpl.java
> +        if (commentRepository.findById(commentId).isEmpty()) {
поправила

2022-10-03 18:08 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentService.java
> +    List<CommentDto> getAll(Long eventId);
изменила. теперь сервис возвращает доменный объект, маппинг происходит в контроллере

2022-10-03 19:13 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentService.java
> +    CommentDto update(Long userId, Long commentId, NewCommentDto newComment);
я не стала изначально делать новое дто, потому что в данном случае у меня по требованиям дто на создание и апдейт идентичны. мне кажется, что когда появится требование на другое дто, тогда и надо переделывать, потому что заранее все возможные будущие нюансы учесть невозможно и не факт, что это пригодится. сейчас добавила сейчас еще одно дто на апдейт

2022-10-03 19:14 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentService.java
> +    CommentDto create(Long userId, Long eventId, NewCommentDto newComment);
во всем проекте были ситуации, когда нужно было делать проверки на null, поэтому я использую обертки. в данном случае это необязательно, но сделано для консистентности всего кода в проекте

2022-10-04 13:10 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentServiceImpl.java
> +                    || commentRepository.findById(commentId).get().getStatus().equals(CommentStatus.PUBLISHED))) {
изменила

2022-10-04 13:13 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentServiceImpl.java
> +            } else {
поменяла

2022-10-04 13:40 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentServiceImpl.java
> +    public CommentDto rejectByAdmin(Long commentId) {
поменяла

2022-10-04 13:56 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/model/event/EventMapper.java
> +                null
в названии подсвечивается, что это расширенный дто, который мы отдаем клиенту, и все расчетные значения я присваиваю объекту в сервисе сеттерами. можно передавать и параметрами, но тогда имеет смысл уже просто переделать работу всех расчетных параметров маппера на такую логику, потому что там не только views так передается. в связи с тем, что для этого нужно переделывать логику во всем проекте, а разницы в общем-то никакой нет, я бы оставила как есть

2022-10-04 15:13 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentService.java
> +    CommentDto create(Long userId, Long eventId, NewCommentDto newComment);
null-ы скорее путают и скорее создают прецендент для NPE. лучше без них и оперировать примитивами

2022-10-04 15:34 UTC, sniskorodnova commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentService.java
> +    CommentDto create(Long userId, Long eventId, NewCommentDto newComment);
хорошо, поменяла

2022-10-05 09:31 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/ewm/service/comment/CommentService.java
> +    CommentDto update(Long userId, Long commentId, NewCommentDto newComment);
> все возможные будущие нюансы учесть невозможно и не факт

все так.

в данном случае твоя задача как архитектора обозначить структуру и установить парадигмы, в которых будет развиваться код. разделяя dto на этапе первой имплементации ты не связываешь эндпоинты между собой и сразу обязываешь развивать их независимо. 

не делая этого, ты можешь столкнуться с ошибкой в будущем. программисты -- ленивый народ. придет кто-то, кто не будет знать о твоих планах на разделение dto-х, и добавит поле в оба эндпоинта, когда требуется только в одном. наверное, это не то, что ты бы хотела

2022-10-05 09:33 UTC, vbutrim commented on ewm-service/src/main/java/ru/practicum/ewm/model/event/EventMapper.java
> +                null
> разницы в общем-то никакой нет

а она есть :) в первом случае у тебя сборка объекта происходит в одном месте, во втором -- расплывается на несколько классов.

2022-10-05 09:34 UTC, vbutrim approved these changes
lgtm

2022-10-05 16:47 UTC, merged